# Site settings
title: Cubicle UX

description: > # this means to ignore newlines until "baseurl:"
  Design patterns, resources and inspiration for enterprise experiences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cubicleux.github.io" # the base hostname & protocol for your site
github_username:  cubicleux

# Build settings
markdown: kramdown
