# Site settings
title: Cubicle UX

description: > # this means to ignore newlines until "baseurl:"
  Interface design patterns, resources and inspiration for enterprise user experiences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cubicleux.github.io" # the base hostname & protocol for your site
github_username:  cubicleux

permalink: /:categories/:title/

# Build settings
markdown: kramdown
paginate: 12
